Sync with upstream lesspipe

diff --git a/scripts/lesspipe b/scripts/lesspipe
--- a/scripts/lesspipe
+++ b/scripts/lesspipe
@@ -11,7 +11,7 @@
 # Further Modifications by Thomas Schoepf <schoepf@debian.org>
 #
 # combined lessfile and lesspipe to avoid duplication of decode stage
-# shell is sure icky.  I'm real tempted to rewrite the whole thing in Perl 
+# shell is sure icky.  I'm real tempted to rewrite the whole thing in Perl
 #
 # Unfortunately, this means that I have filename dependencies sprinkled
 # throughout the code.  If you don't want lessfile to be called that,
@@ -84,7 +84,7 @@ if [ $# -eq 1 ] ; then
 		TMPFILE=`tempfile -d $TMPDIR -p lessf`
 		if [ -z "$TMPFILE" ]; then
 			echo >&2 "Could not find essential program 'tempfile'. Exiting"
-			exit 1
+      exit 1
 		fi
 	fi
 
@@ -110,6 +110,10 @@ if [ $# -eq 1 ] ; then
 
 		# Decode file for less
 		case `echo "$1" | tr '[:upper:]' '[:lower:]'` in
+			*.a)
+				if [ -x "`which ar`" ]; then ar tv "$1"
+				else echo "No ar available"; fi ;;
+
 			*.arj)
 				if [ -x "`which unarj`" ]; then unarj l "$1"
 				else echo "No unarj available"; fi ;;
@@ -127,16 +131,24 @@ if [ $# -eq 1 ] ; then
 				if [ -x "`which bunzip2`" ]; then bunzip2 -dc "$1"
 				else echo "No bunzip2 available"; fi ;;
 
-			*.deb|*.udeb)
+			*.deb|*.udeb|*.ddeb)
 				echo "$1:"; dpkg --info "$1"
 				echo
 				echo '*** Contents:'; dpkg-deb --contents "$1"
 				;;
 
 			*.doc)
-				if [ -x "`which catdoc`" ]; then catdoc "$1"
+				if [ -x "`which catdoc`" ]; then
+					catdoc "$1"
 				elif [ -x "`which wvText`" -a -e /dev/stdout ]; then
 					wvText "$1" /dev/stdout
+				else
+					# no catdoc or wvText, read normally if file is text.
+					if ( file "$1" | grep ASCII 2>/dev/null >/dev/null); then
+						cat "$1"
+					else
+						echo "No catdoc available";
+					fi
 				fi
 				ms_summary "$1"
 				;;
@@ -227,6 +239,34 @@ if [ $# -eq 1 ] ; then
 				if [ -x "`which lha`" ]; then lha v "$1"
 				else echo "No lha available"; fi ;;
 
+			*.tar.lz|*.tlz)
+				if [ -x "`which lzip`" ]; then
+					lzip -dc "$1" | tar tvvf -
+				elif [ -x "`which lunzip`" ]; then
+					lunzip -dc "$1" | tar tvvf -
+				else echo "No lzip or lunzip available"; fi ;;
+
+			*.lz)
+				if [ -x "`which lzip`" ]; then lzip -dc "$1"
+				elif [ -x "`which lunzip`" ]; then lunzip -dc "$1"
+				else echo "No lzip or lunzip available"; fi ;;
+
+			*.tar.lzma)
+				if [ -x "`which lzma`" ]; then
+					lzma -dc "$1" | tar tfvv -
+				else
+					echo "No lzma available"
+				fi
+				;;
+
+			*.lzma)
+				if [ -x "`which lzma`" ]; then
+					lzma -dc "$1"
+				else
+					echo "No lzma available"
+				fi
+				;;
+
 			*.dvi)
 				if [ -x "`which catdvi`"]; then catdvi "$1"; fi ;;
 
@@ -258,7 +298,8 @@ if [ $# -eq 1 ] ; then
 				else echo "rpm isn't available, no query on rpm package possible"; fi ;;
 
 			*.tar.gz|*.tgz|*.tar.z|*.tar.dz)
-				tar tzvf "$1" ;;
+				tar tzvf "$1" --force-local
+				;;
 
 			# Note that this is out of alpha order so that we don't catch
 			# the gzipped tar files.
@@ -266,7 +307,8 @@ if [ $# -eq 1 ] ; then
 				gzip -dc "$1" ;;
 
 			*.tar)
-				tar tvf "$1" ;;
+				tar tvf "$1" --force-local
+				;;
 
 			*.jar|*.war|*.ear|*.xpi|*.zip)
 				if [ -x "`which unzip`" ]; then unzip -v "$1";
@@ -278,10 +320,9 @@ if [ $# -eq 1 ] ; then
 				if [ -x "`which cabextract`" ]; then cabextract -l "$1"; fi ;;
 
 			*.7z)
-				if [ -x "`which 7zr`" ]; then 7zr l "$1"
-				elif [ -x "`which 7z`" ]; then 7z l "$1"
-				elif [ -x "`which 7za`" ]; then 7za l "$1"
-				else echo "No 7zr, 7z or 7za available"; fi ;;
+				if [ -x "`which 7za`" ]; then 7za l "$1";
+                                elif [ -x "`which 7zr`" ]; then 7zr l "$1";
+				else echo "No 7za or 7zr available"; fi ;;
 
 			*.zoo)
 				if [ -x "`which zoo`" ]; then zoo v "$1";
@@ -300,6 +341,8 @@ if [ $# -eq 1 ] ; then
 
 			*.flac)
 				if [ -x "`which metaflac`" ]; then metaflac --list "$1"; fi ;;
+			*.aac|*.m4a)
+				if [ -x "`which AtomicParsley`" ]; then AtomicParsley "$1" -t 1; fi ;;
 		esac
 	) 2>/dev/null
 
@@ -317,11 +360,11 @@ elif [ $# -eq 2 ] ; then
 	# delete the file created if we were lessfile
 	#
 	if [ $BASENAME = $LESSFILE ]; then
-    if [ -n "$BASH" ]; then
-      if [ ! -O "$2" ]; then
-        echo "Error in deleting $2" > /dev/tty
-      fi
-    fi
+		if [ -n "$BASH" ]; then
+			if [ ! -O "$2" ]; then
+				echo "Error in deleting $2" > /dev/tty
+			fi
+		fi
 
 		if [ -f "$2" ]; then
 			rm -f "$2"
